FROM node:16

ADD . /frontend
WORKDIR /frontend
COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .
#COPY ./ ./

RUN npm run build 

EXPOSE 3000

CMD ["npm", "start"]

#CMD ["npm", "run", "start"]