version: '3'

services:
  usersdb:
    build: ./db/users
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3307"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  front:
    build: ./frontend
    depends_on:
      usersdb:
        condition: service_healthy
    ports:
      - "3000:3000"
  back:
    build: ./properties
    depends_on:
      usersdb:
        condition: service_healthy
    ports:
      - "8090:8090"
  messages:
    build: ./messages
    ports: 
      - "8070:8070"
  consumer:
    build: ./consumer
    depends_on:
      rabbit:
        condition: service_healthy
  search:
    build: ./search
    ports:
      - "8000:8000"
  users:
    build: ./users
    depends_on:
      usersdb:
        condition: service_healthy
    ports:
      - "9000:9000"


  rabbit:
      container_name: rabbit
      image: rabbitmq:3-management
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - "5671:5671"
        - "5672:5672"
        - "8080:15672"
      healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 1s
        timeout: 20s
        retries: 30
  