version: '3'

services:
  usersdb:
    build: ./db/users
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
<<<<<<< HEAD
=======
  mongo_db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_DATA_DIR: /data/db
        MONGO_INITDB_DATABASE: Properties
      ports:
        - "27017:27017"      
  solr:
    container_name: solr
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./docker/solr/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - property
>>>>>>> 075f76dbcdc5d926cb1c47d640487344d811b21c
  rabbit:
      container_name: rabbit
      image: rabbitmq:3-management
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      volumes:
      - ./docker/rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
      ports:
        - "5671:5671"
        - "5672:5672"
        - "8080:15672"
      healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 1s
        timeout: 20s
        retries: 30
<<<<<<< HEAD
  solr:
    container_name: solr
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./docker/solr/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - property
=======
>>>>>>> 075f76dbcdc5d926cb1c47d640487344d811b21c
  memcached:
    container_name: cache
    image: memcached
    ports:
      - "11211:11211"
<<<<<<< HEAD
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_DATABASE: Properties
    ports:
      - "27017:27017"          
=======

>>>>>>> 075f76dbcdc5d926cb1c47d640487344d811b21c
  back:
    build: ./properties
    depends_on:
      mongo_db: 
        condition: service_started
    ports:
      - "8090:8090"

  messages:
    build: ./messages
    depends_on:
      mongo_db: 
        condition: service_started
    ports: 
      - "8070:8070"
  consumer:
    build: ./consumer
    depends_on:
      rabbit:
        condition: service_healthy
      search:
        condition: service_started
  search:
    build: ./search
    ports:
      - "8000:8000"
  users:
    build: ./users
    depends_on:
      usersdb:
        condition: service_healthy
    ports:
      - "9000:9000"
<<<<<<< HEAD
=======

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
  
>>>>>>> 075f76dbcdc5d926cb1c47d640487344d811b21c
