FROM golang:1.17

ADD . /consumersearch

WORKDIR /consumersearch
RUN go mod init consumersearch
RUN go mod tidy
RUN go build -o consumersearch .
RUN chmod +x /consumersearch

ENTRYPOINT ["/consumersearch/consumersearch"]